version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    ports:
        - 8080:8080
    environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: db
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: keycloak
        DB_SCHEMA: public
        KEYCLOAK_HOSTNAME: localhost
        KEYCLOAK_USER: kc_admin
        KEYCLOAK_PASSWORD: kc_admin
    volumes:
        - ./data:/opt/jboss/keycloak/standalone/data
    depends_on:
        - db
    ports:
        - 8180:8080

  db:
    image: postgres:latest
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
        POSTGRES_DB: keycloak
    ports:
        - 5433:5433