---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmaps.yml
- ingress.yml

replicas:
- count: 2
  name: precatorio

patchesStrategicMerge:
- |
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: precatorio
  spec:
    template:
      spec:
        containers:
        - name: precatorio
          env:
          - name: JAVA_TOOL_OPTIONS
            value: '-javaagent:/opt/glowroot/glowroot.jar -Dglowroot.agent.id=precatorio-prd::
              -Dglowroot.collector.address=https://glowroot-central-grpc.prd.cnj.cloud:443'
          volumeMounts:
          - mountPath: /opt/glowroot
            name: glowroot-agent
        initContainers:
        - name: glowroot-agent
          image: registry.cnj.jus.br/glowroot-agent:0.13
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /glowroot
            name: glowroot-agent
        volumes:
        - emptyDir: {}
          name: glowroot-agent
...
